import { Link } from 'react-router-dom';

export default function PrivacyPage() {
  return (
    <div style={styles.page}>
      <h1 style={styles.title}>Privacy & Medical Disclaimer</h1>

      <section style={styles.section}>
        <h2 style={styles.h2}>⚠️ Not Medical Advice</h2>
        <p style={styles.p}>
          HealthAI is a student-built fitness tracker and wellness companion. The recommendations,
          plans, food analyses, and chat responses generated by this app are informational only and
          are <strong>not a substitute for professional medical advice, diagnosis, or treatment</strong>.
        </p>
        <p style={styles.p}>
          Always consult a qualified healthcare provider before:
        </p>
        <ul style={styles.ul}>
          <li>Starting a new exercise program</li>
          <li>Making significant changes to your diet</li>
          <li>Acting on any recommendation if you have a pre-existing health condition</li>
          <li>Taking any action in response to symptoms or concerns</li>
        </ul>
        <p style={styles.p}>
          If you experience a medical emergency, call 911 (US) or your local emergency number immediately.
        </p>
      </section>

      <section style={styles.section}>
        <h2 style={styles.h2}>What We Store</h2>
        <p style={styles.p}>
          HealthAI stores the health data you log (steps, sleep, nutrition, activities, goals), your
          profile (age, weight, health conditions, dietary restrictions), and your chat history with
          the AI coach. This data lives in a local SQLite database on the server.
        </p>
        <p style={styles.p}>
          Your data is never shared with third parties, sold, or used for advertising. Your data is
          only sent to Anthropic's Claude API when you explicitly request an AI feature (chat, food
          scan, or plan generation), and only the minimum context needed is sent.
        </p>
      </section>

      <section style={styles.section}>
        <h2 style={styles.h2}>Your Rights</h2>
        <p style={styles.p}>
          You can export all of your data as JSON, or delete your account and all associated records,
          at any time from the <Link to="/profile" style={styles.link}>Profile</Link> page.
        </p>
      </section>

      <section style={styles.section}>
        <h2 style={styles.h2}>Academic Context</h2>
        <p style={styles.p}>
          HealthAI is a senior project built for educational purposes. It is not a commercial product,
          is not HIPAA-certified, and should not be used to store information you would not comfortably
          share with a class instructor.
        </p>
      </section>
    </div>
  );
}

const styles: Record<string, React.CSSProperties> = {
  page: { padding: '32px 24px', maxWidth: '800px', margin: '0 auto', color: 'var(--text)' },
  title: { fontSize: '28px', fontWeight: 700, marginBottom: '24px', color: 'var(--text)' },
  section: { marginBottom: '28px' },
  h2: { fontSize: '18px', fontWeight: 600, marginBottom: '10px', color: 'var(--text)' },
  p: { fontSize: '14px', lineHeight: 1.6, color: 'var(--text-secondary)', marginBottom: '10px' },
  ul: { fontSize: '14px', lineHeight: 1.8, color: 'var(--text-secondary)', paddingLeft: '20px', marginBottom: '10px' },
  link: { color: 'var(--accent)', textDecoration: 'underline' },
};
